project_name: wally

builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    targets:
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w

brews:
  -
    # Default to project name
    name: wally

    tap:
      owner: ltpquang
      name: homebrew-tap

    # Template for the url which is determined by the given Token (github or gitlab)
    # Default for github is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    # Default for gitlab is "https://gitlab.com/<repo_owner>/<repo_name>/-/releases/{{ .Tag }}/downloads/{{ .ArtifactName }}"
    # Default for gitea is "https://gitea.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_template: "https://github.com/ltpquang/wally/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: ltpquang
      email: phuc.quang102@gmail.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/ltpquang/wally"

    # Template of your app's description.
    # Default is empty.
    description: "Randomly change wallpaper using Unsplash Source"

archives:
  - #Replacements for GOOS and GOARCH in the archive name
    replacements:
      darwin: macOS
      amd64: x86_64

    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - "^*.md:"
